/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVendasRouteImport } from './routes/_app/vendas'
import { Route as AppTemplatesRouteImport } from './routes/_app/templates'
import { Route as AppProdutosRouteImport } from './routes/_app/produtos'
import { Route as AppPdvRouteImport } from './routes/_app/pdv'
import { Route as AppHistoricoVendasRouteImport } from './routes/_app/historico-vendas'
import { Route as AppIntegracoesWhatsappRouteImport } from './routes/_app/integracoes.whatsapp'
import { Route as AppIntegracoesBancoInterRouteImport } from './routes/_app/integracoes.banco-inter'
import { Route as AppFinanceiroRelatoriosCaixaRouteImport } from './routes/_app/financeiro.relatorios-caixa'
import { Route as AppFinanceiroReceberRouteImport } from './routes/_app/financeiro.receber'
import { Route as AppFinanceiroPagarRouteImport } from './routes/_app/financeiro.pagar'
import { Route as AppFinanceiroDashboardRouteImport } from './routes/_app/financeiro.dashboard'
import { Route as AppFinanceiroCurvaAbcRouteImport } from './routes/_app/financeiro.curva-abc'
import { Route as AppFinanceiroBalanceteRouteImport } from './routes/_app/financeiro.balancete'
import { Route as AppConfigUsuariosRouteImport } from './routes/_app/config.usuarios'
import { Route as AppConfigPlanoContasRouteImport } from './routes/_app/config.plano-contas'
import { Route as AppConfigOperadoresRouteImport } from './routes/_app/config.operadores'
import { Route as AppCadastrosFornecedoresRouteImport } from './routes/_app/cadastros.fornecedores'
import { Route as AppCadastrosClientesRouteImport } from './routes/_app/cadastros.clientes'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVendasRoute = AppVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutosRoute = AppProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AppRoute,
} as any)
const AppPdvRoute = AppPdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoricoVendasRoute = AppHistoricoVendasRouteImport.update({
  id: '/historico-vendas',
  path: '/historico-vendas',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegracoesWhatsappRoute = AppIntegracoesWhatsappRouteImport.update({
  id: '/integracoes/whatsapp',
  path: '/integracoes/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegracoesBancoInterRoute =
  AppIntegracoesBancoInterRouteImport.update({
    id: '/integracoes/banco-inter',
    path: '/integracoes/banco-inter',
    getParentRoute: () => AppRoute,
  } as any)
const AppFinanceiroRelatoriosCaixaRoute =
  AppFinanceiroRelatoriosCaixaRouteImport.update({
    id: '/financeiro/relatorios-caixa',
    path: '/financeiro/relatorios-caixa',
    getParentRoute: () => AppRoute,
  } as any)
const AppFinanceiroReceberRoute = AppFinanceiroReceberRouteImport.update({
  id: '/financeiro/receber',
  path: '/financeiro/receber',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroPagarRoute = AppFinanceiroPagarRouteImport.update({
  id: '/financeiro/pagar',
  path: '/financeiro/pagar',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroDashboardRoute = AppFinanceiroDashboardRouteImport.update({
  id: '/financeiro/dashboard',
  path: '/financeiro/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroCurvaAbcRoute = AppFinanceiroCurvaAbcRouteImport.update({
  id: '/financeiro/curva-abc',
  path: '/financeiro/curva-abc',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroBalanceteRoute = AppFinanceiroBalanceteRouteImport.update({
  id: '/financeiro/balancete',
  path: '/financeiro/balancete',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigUsuariosRoute = AppConfigUsuariosRouteImport.update({
  id: '/config/usuarios',
  path: '/config/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigPlanoContasRoute = AppConfigPlanoContasRouteImport.update({
  id: '/config/plano-contas',
  path: '/config/plano-contas',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigOperadoresRoute = AppConfigOperadoresRouteImport.update({
  id: '/config/operadores',
  path: '/config/operadores',
  getParentRoute: () => AppRoute,
} as any)
const AppCadastrosFornecedoresRoute =
  AppCadastrosFornecedoresRouteImport.update({
    id: '/cadastros/fornecedores',
    path: '/cadastros/fornecedores',
    getParentRoute: () => AppRoute,
  } as any)
const AppCadastrosClientesRoute = AppCadastrosClientesRouteImport.update({
  id: '/cadastros/clientes',
  path: '/cadastros/clientes',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/historico-vendas': typeof AppHistoricoVendasRoute
  '/pdv': typeof AppPdvRoute
  '/produtos': typeof AppProdutosRoute
  '/templates': typeof AppTemplatesRoute
  '/vendas': typeof AppVendasRoute
  '/cadastros/clientes': typeof AppCadastrosClientesRoute
  '/cadastros/fornecedores': typeof AppCadastrosFornecedoresRoute
  '/config/operadores': typeof AppConfigOperadoresRoute
  '/config/plano-contas': typeof AppConfigPlanoContasRoute
  '/config/usuarios': typeof AppConfigUsuariosRoute
  '/financeiro/balancete': typeof AppFinanceiroBalanceteRoute
  '/financeiro/curva-abc': typeof AppFinanceiroCurvaAbcRoute
  '/financeiro/dashboard': typeof AppFinanceiroDashboardRoute
  '/financeiro/pagar': typeof AppFinanceiroPagarRoute
  '/financeiro/receber': typeof AppFinanceiroReceberRoute
  '/financeiro/relatorios-caixa': typeof AppFinanceiroRelatoriosCaixaRoute
  '/integracoes/banco-inter': typeof AppIntegracoesBancoInterRoute
  '/integracoes/whatsapp': typeof AppIntegracoesWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/historico-vendas': typeof AppHistoricoVendasRoute
  '/pdv': typeof AppPdvRoute
  '/produtos': typeof AppProdutosRoute
  '/templates': typeof AppTemplatesRoute
  '/vendas': typeof AppVendasRoute
  '/cadastros/clientes': typeof AppCadastrosClientesRoute
  '/cadastros/fornecedores': typeof AppCadastrosFornecedoresRoute
  '/config/operadores': typeof AppConfigOperadoresRoute
  '/config/plano-contas': typeof AppConfigPlanoContasRoute
  '/config/usuarios': typeof AppConfigUsuariosRoute
  '/financeiro/balancete': typeof AppFinanceiroBalanceteRoute
  '/financeiro/curva-abc': typeof AppFinanceiroCurvaAbcRoute
  '/financeiro/dashboard': typeof AppFinanceiroDashboardRoute
  '/financeiro/pagar': typeof AppFinanceiroPagarRoute
  '/financeiro/receber': typeof AppFinanceiroReceberRoute
  '/financeiro/relatorios-caixa': typeof AppFinanceiroRelatoriosCaixaRoute
  '/integracoes/banco-inter': typeof AppIntegracoesBancoInterRoute
  '/integracoes/whatsapp': typeof AppIntegracoesWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/historico-vendas': typeof AppHistoricoVendasRoute
  '/_app/pdv': typeof AppPdvRoute
  '/_app/produtos': typeof AppProdutosRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/_app/vendas': typeof AppVendasRoute
  '/_app/cadastros/clientes': typeof AppCadastrosClientesRoute
  '/_app/cadastros/fornecedores': typeof AppCadastrosFornecedoresRoute
  '/_app/config/operadores': typeof AppConfigOperadoresRoute
  '/_app/config/plano-contas': typeof AppConfigPlanoContasRoute
  '/_app/config/usuarios': typeof AppConfigUsuariosRoute
  '/_app/financeiro/balancete': typeof AppFinanceiroBalanceteRoute
  '/_app/financeiro/curva-abc': typeof AppFinanceiroCurvaAbcRoute
  '/_app/financeiro/dashboard': typeof AppFinanceiroDashboardRoute
  '/_app/financeiro/pagar': typeof AppFinanceiroPagarRoute
  '/_app/financeiro/receber': typeof AppFinanceiroReceberRoute
  '/_app/financeiro/relatorios-caixa': typeof AppFinanceiroRelatoriosCaixaRoute
  '/_app/integracoes/banco-inter': typeof AppIntegracoesBancoInterRoute
  '/_app/integracoes/whatsapp': typeof AppIntegracoesWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/historico-vendas'
    | '/pdv'
    | '/produtos'
    | '/templates'
    | '/vendas'
    | '/cadastros/clientes'
    | '/cadastros/fornecedores'
    | '/config/operadores'
    | '/config/plano-contas'
    | '/config/usuarios'
    | '/financeiro/balancete'
    | '/financeiro/curva-abc'
    | '/financeiro/dashboard'
    | '/financeiro/pagar'
    | '/financeiro/receber'
    | '/financeiro/relatorios-caixa'
    | '/integracoes/banco-inter'
    | '/integracoes/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/historico-vendas'
    | '/pdv'
    | '/produtos'
    | '/templates'
    | '/vendas'
    | '/cadastros/clientes'
    | '/cadastros/fornecedores'
    | '/config/operadores'
    | '/config/plano-contas'
    | '/config/usuarios'
    | '/financeiro/balancete'
    | '/financeiro/curva-abc'
    | '/financeiro/dashboard'
    | '/financeiro/pagar'
    | '/financeiro/receber'
    | '/financeiro/relatorios-caixa'
    | '/integracoes/banco-inter'
    | '/integracoes/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/historico-vendas'
    | '/_app/pdv'
    | '/_app/produtos'
    | '/_app/templates'
    | '/_app/vendas'
    | '/_app/cadastros/clientes'
    | '/_app/cadastros/fornecedores'
    | '/_app/config/operadores'
    | '/_app/config/plano-contas'
    | '/_app/config/usuarios'
    | '/_app/financeiro/balancete'
    | '/_app/financeiro/curva-abc'
    | '/_app/financeiro/dashboard'
    | '/_app/financeiro/pagar'
    | '/_app/financeiro/receber'
    | '/_app/financeiro/relatorios-caixa'
    | '/_app/integracoes/banco-inter'
    | '/_app/integracoes/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vendas': {
      id: '/_app/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AppVendasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/produtos': {
      id: '/_app/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AppProdutosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pdv': {
      id: '/_app/pdv'
      path: '/pdv'
      fullPath: '/pdv'
      preLoaderRoute: typeof AppPdvRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/historico-vendas': {
      id: '/_app/historico-vendas'
      path: '/historico-vendas'
      fullPath: '/historico-vendas'
      preLoaderRoute: typeof AppHistoricoVendasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integracoes/whatsapp': {
      id: '/_app/integracoes/whatsapp'
      path: '/integracoes/whatsapp'
      fullPath: '/integracoes/whatsapp'
      preLoaderRoute: typeof AppIntegracoesWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integracoes/banco-inter': {
      id: '/_app/integracoes/banco-inter'
      path: '/integracoes/banco-inter'
      fullPath: '/integracoes/banco-inter'
      preLoaderRoute: typeof AppIntegracoesBancoInterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro/relatorios-caixa': {
      id: '/_app/financeiro/relatorios-caixa'
      path: '/financeiro/relatorios-caixa'
      fullPath: '/financeiro/relatorios-caixa'
      preLoaderRoute: typeof AppFinanceiroRelatoriosCaixaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro/receber': {
      id: '/_app/financeiro/receber'
      path: '/financeiro/receber'
      fullPath: '/financeiro/receber'
      preLoaderRoute: typeof AppFinanceiroReceberRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro/pagar': {
      id: '/_app/financeiro/pagar'
      path: '/financeiro/pagar'
      fullPath: '/financeiro/pagar'
      preLoaderRoute: typeof AppFinanceiroPagarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro/dashboard': {
      id: '/_app/financeiro/dashboard'
      path: '/financeiro/dashboard'
      fullPath: '/financeiro/dashboard'
      preLoaderRoute: typeof AppFinanceiroDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro/curva-abc': {
      id: '/_app/financeiro/curva-abc'
      path: '/financeiro/curva-abc'
      fullPath: '/financeiro/curva-abc'
      preLoaderRoute: typeof AppFinanceiroCurvaAbcRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro/balancete': {
      id: '/_app/financeiro/balancete'
      path: '/financeiro/balancete'
      fullPath: '/financeiro/balancete'
      preLoaderRoute: typeof AppFinanceiroBalanceteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config/usuarios': {
      id: '/_app/config/usuarios'
      path: '/config/usuarios'
      fullPath: '/config/usuarios'
      preLoaderRoute: typeof AppConfigUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config/plano-contas': {
      id: '/_app/config/plano-contas'
      path: '/config/plano-contas'
      fullPath: '/config/plano-contas'
      preLoaderRoute: typeof AppConfigPlanoContasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config/operadores': {
      id: '/_app/config/operadores'
      path: '/config/operadores'
      fullPath: '/config/operadores'
      preLoaderRoute: typeof AppConfigOperadoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cadastros/fornecedores': {
      id: '/_app/cadastros/fornecedores'
      path: '/cadastros/fornecedores'
      fullPath: '/cadastros/fornecedores'
      preLoaderRoute: typeof AppCadastrosFornecedoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cadastros/clientes': {
      id: '/_app/cadastros/clientes'
      path: '/cadastros/clientes'
      fullPath: '/cadastros/clientes'
      preLoaderRoute: typeof AppCadastrosClientesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppHistoricoVendasRoute: typeof AppHistoricoVendasRoute
  AppPdvRoute: typeof AppPdvRoute
  AppProdutosRoute: typeof AppProdutosRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppVendasRoute: typeof AppVendasRoute
  AppCadastrosClientesRoute: typeof AppCadastrosClientesRoute
  AppCadastrosFornecedoresRoute: typeof AppCadastrosFornecedoresRoute
  AppConfigOperadoresRoute: typeof AppConfigOperadoresRoute
  AppConfigPlanoContasRoute: typeof AppConfigPlanoContasRoute
  AppConfigUsuariosRoute: typeof AppConfigUsuariosRoute
  AppFinanceiroBalanceteRoute: typeof AppFinanceiroBalanceteRoute
  AppFinanceiroCurvaAbcRoute: typeof AppFinanceiroCurvaAbcRoute
  AppFinanceiroDashboardRoute: typeof AppFinanceiroDashboardRoute
  AppFinanceiroPagarRoute: typeof AppFinanceiroPagarRoute
  AppFinanceiroReceberRoute: typeof AppFinanceiroReceberRoute
  AppFinanceiroRelatoriosCaixaRoute: typeof AppFinanceiroRelatoriosCaixaRoute
  AppIntegracoesBancoInterRoute: typeof AppIntegracoesBancoInterRoute
  AppIntegracoesWhatsappRoute: typeof AppIntegracoesWhatsappRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHistoricoVendasRoute: AppHistoricoVendasRoute,
  AppPdvRoute: AppPdvRoute,
  AppProdutosRoute: AppProdutosRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppVendasRoute: AppVendasRoute,
  AppCadastrosClientesRoute: AppCadastrosClientesRoute,
  AppCadastrosFornecedoresRoute: AppCadastrosFornecedoresRoute,
  AppConfigOperadoresRoute: AppConfigOperadoresRoute,
  AppConfigPlanoContasRoute: AppConfigPlanoContasRoute,
  AppConfigUsuariosRoute: AppConfigUsuariosRoute,
  AppFinanceiroBalanceteRoute: AppFinanceiroBalanceteRoute,
  AppFinanceiroCurvaAbcRoute: AppFinanceiroCurvaAbcRoute,
  AppFinanceiroDashboardRoute: AppFinanceiroDashboardRoute,
  AppFinanceiroPagarRoute: AppFinanceiroPagarRoute,
  AppFinanceiroReceberRoute: AppFinanceiroReceberRoute,
  AppFinanceiroRelatoriosCaixaRoute: AppFinanceiroRelatoriosCaixaRoute,
  AppIntegracoesBancoInterRoute: AppIntegracoesBancoInterRoute,
  AppIntegracoesWhatsappRoute: AppIntegracoesWhatsappRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
